# Generated by Django 4.2.4 on 2023-09-22 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_category_parent'),
        ('accounts', '0003_alter_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='subscription_categories',
            field=models.ManyToManyField(related_name='subscribtion_categories', to='main.category', verbose_name='Категории для рассылки'),
        ),
        migrations.AddField(
            model_name='profile',
            name='telegram',
            field=models.CharField(max_length=40, null=True, verbose_name='Телеграм'),
        ),
    ]
