# Generated by Django 4.2.4 on 2023-10-04 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_subscription_categories_profile_telegram'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='telegram',
        ),
    ]
