# Generated by Django 4.2.4 on 2023-09-14 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_news_post_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='post_views',
            field=models.PositiveIntegerField(default=0, verbose_name='Просмотры'),
        ),
    ]
