# Generated by Django 4.2.4 on 2023-10-03 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_category_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(null=True, upload_to='news_images/', verbose_name='Изображение'),
        ),
    ]
